### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by flowridr** [claudiusli/csv-import#2]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 18: invalid continuation byte

**Comment by claudiusli** [comment]
Can you send the csv file that it's throwing that error on?
It sounds like it has a character that isn't in utf-8.

**Comment by flowridr** [comment]
Hi,

The whole file is encoded with iso-8859-1. I changed the encoding to utf-8 and now it works.
